config/routes.rb
Rails.application.routes.draw do
  get 'profile/edit_profile'
  post 'profile/edit_profile'
  
  get 'password/forget_password'
  post 'password/forget_password'

  get 'password/reset_password'
  post 'password/reset_password'

  get 'account/signup'
  post 'account/signup'


  get 'account/login'
  post 'account/login'

  get 'account/dashboard'
  get 'account/logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    validates :email, uniqueness: true, length: { in: 5..50}#, format: { with: /^[^@][\w.-]+[.][a-z]{2,4}$/i/,messages: "Only letters allowed"}
    validates :password ,presence: true,confirmation: true, length: {  in: 4..20 }, on: :create

    has_one_attached :profile_pic
    before_save :encrypt_password


    def self.authenticate(email,password)
        user = find_by_email(email)
        return user if user && user.authenticated_password(password)
    end

    def authenticated_password(password)
        self.encrypted_password == encrypt(password) 
    end


    protected
    def encrypt_password
        return if password.blank?
        self.encrypted_password = encrypt(password) 
    end

    def encrypt(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def signup
    @user = User.new
    if request.post?
      @user = User.new(user_params)
      if @user.save
        UserNotifierMailer.signup_alert(@user).deliver

        redirect_to :action=>"login"

      else
        render :action=>"signup"
      end
    end
  end

  def login
    if request.post?
      @user = User.authenticate(params[:email],params[:password])
      if @user
        session[:user] = @user.id
        redirect_to :action=>:dashboard
      else
        flash[:notice] = "Invalid email/password"
        render :action=>:login
      end
    end
  end

  def logout 
    session.delete(:user)
    redirect_to account_login_url
  end

  def user_params
    params.permit(:first_name,:last_name,:mobile,:email,:date_of_birth,:password,:password_confirmation,:encrypted_password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  def forget_password
    if request.post?
      @user = User.find_by_email(params[:email])
      if @user
        new_password = create_random_password
        @user.update(password: new_password)
        puts "=========="
        puts new_password

        redirect_to account_login_url
        
        
      else
        flash[:notice] = "Invalid email id .please enter a valid email"
        render :action=>:"forget_password"
      end

    end
  end

    def create_random_password
      (0...6).map {(65 + rand(26)).chr }.join
    end

  def reset_password
    @user = User.find(session[:user])
    if request.post?
    if @user
      #unless params[:password].nil || params[:password] == "" ||params[:password] == nil
      if @user.update(:password=>params[:password])
      #acton mailer
      flash[:notice] = "Your password has been reset."
      redirect_to account_dashboard_url
      else
      flash[:notice] = "enter valid password"
      render :action=>:reset_password
      end
    end
  end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def edit_profile
    @user = User.find(session[:user])
    if request.post?
      if @user
    if @user.update(user_params)
      redirect_to account_dashboard_url
    else
      render :action=>:edit_profile
    end
    end
  end
end

  def user_params
    params.permit(:first_name,:last_name,:mobile,:date_of_birth,:profile_pic)
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <p class="navbar-text float-right">
<% if session[:user] %>
  <%= link_to "Edit profile",profile_edit_profile_path %> | <%= link_to :"Reset_Password", password_reset_password_path %> |
  <%= link_to "Logout", account_login_path %>

<% else %>
  <%= link_to "Sign up", account_signup_path  %> |
  <%= link_to "Login", account_login_path %>
<% end %>
</p>
  <input type="checkbox" id="flip">
  <div class="cover">
    <div class="front">
      <img src="/assets/frontImg.jpg" alt="">
      <div class="text">
        <span class="text-1">Every new friend is a <br> new adventure</span>
        <span class="text-2">Let's get connected</span>
      </div>
    </div>
    <div class="back">
      <img class="backImg" src="/assets/backImg.jpg" alt="">
      <div class="text">
        <span class="text-1">Complete miles of journey <br> with one step</span>
        <span class="text-2">Let's get started</span>
      </div>
    </div>
  </div>
  <div class="forms">
      <%= yield %>
      </form>
    </div>
    </div>
  </div>
  </div>
  </body>
</html>

app/views/password/forget_password.html.erb
<h2>Forget your password?</h2>
<%= flash[:notice] %>

<%= form_with url: "/password/forget_password", method: :post do |f| %>

    <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
    </div>

<br />
    <div class="actions">
    <%= f.submit "Get New Password"%>
    </div>
<% end %>

app/views/password/reset_password.html.erb
<h2>Forget your password?</h2>
<%= flash[:notice] %>
<%= form_with url: "/password/reset_password", method: :post do |f| %>
    <% if @user.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
     </div>
    <% end %>
    <div class="field">
     <%= f.label :new_password %><br />
     <%= f.password_field :password %>
    </div>
    <div class="field">
     <%= f.label :confirm_new_password %><br />
     <%= f.password_field :password_confirmation %>
    </div>

<br />
    <div class="actions">
    <%= f.submit "Change Password"%>
    </div>
<% end %>